# line length
margin = 100


# indent
indent = 4


# blank line
format_docstrings = true


# break funtion parameters when they are too long
always_for_in = true
join_lines_based_on_source = false


# format dicts
whitespace_typedefs = true


# order for using/import
align_matrix = false
