name = "GCATCodes"
uuid = "604ddfb8-b057-4e57-a88a-fd8ef85a1bc4"
version = "1.0.0-DEV"
authors = ["Filip Cavar"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
CairoMakie = "0.15.7"
GraphMakie = "0.6.3"
Graphs = "1.13.2"
Logging = "1.11.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
